import orval, { defineConfig } from 'orval'

// eslint-disable-next-line import/no-default-export -- Orval expects a default export for config
export default defineConfig({
  'spa-config': {
    input: {
      target: './petstore.yaml',
    },
    output: {
      client: 'react-query',
      workspace: 'src/api/',
      target: 'index.ts',
      mode: 'split',
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: '../mutator/client.ts',
          name: 'client',
        },
        operations: {
          listPets: {
            requestOptions: {
              timeout: 30000,
            },
          },
        },
        /*
        header: (info) => {
          return [
            `tslint:disable`,
            `eslint-disable`,
            `Generated by orval 🍺`,
            `Do not edit manually.`,
            ...(info.title ? [info.title] : []),
            ...(info.description ? [info.description] : []),
          ]
        },
        */
      },
    },
  },
})
